export const AUTH__SET_STATE = '[AUTH] SET_STATE';
export const AUTH__SET_TOKEN = '[AUTH] SET_TOKEN';
export const AUTH__SET_LOADING = '[AUTH] SET_LOADING';
export const AUTH__SET_IS_LOGIN_ERROR = '[AUTH] SET_IS_LOGIN_ERROR';
export const AUTH__SET_LOGIN_ERROR = '[AUTH] SET_LOGIN_ERROR';
export const AUTH__LOGIN = '[AUTH] LOGIN';
export const AUTH__LOGOUT = '[AUTH] LOGOUT';
export const AUTH__RESET_DATA = '[AUTH] RESET_DATA';
export const AUTH__REGISTER = '[AUTH] REGISTER';
export const AUTH__SET_REGISTER_ERROR = '[AUTH] SET_REGISTER_ERROR';
export const AUTH__SET_IS_REGISTERED = '[AUTH] SET_IS_REGISTERED';

export const USER__FETCH = '[USER] FETCH';
export const USER__SET_DATA = '[USER] SET_DATA';
export const USER__SET_LOADING = '[USER] SET_LOADING';

export const ROOM__FETCH_ROOMS = '[ROOM] FETCH';
export const ROOM__FETCH_SELECTED_ROOM = '[ROOM] FETCH';
export const ROOM__SET_ROOMS = '[ROOM] SET_ROOMS';
export const ROOM__SET_SELECTED_ROOM = '[ROOM] SET_SELECTED_ROOM';
export const ROOM__SET_LOADING = '[ROOM] SET_LOADING';

export const MESSAGE__POST = '[MESSAGE] POST';
export const MESSAGE__SET_DATA = '[MESSAGE] SET_DATA';
export const MESSAGE__SET_LOADING = '[MESSAGE] SET_LOADING';
export const MESSAGE__SET_IS_ERROR = '[MESSAGE] SET_IS_ERROR';
